### ISSUE TITLE
识别错误，python版能识别正确

### ISSUE THREAD

**Issue by iebcn309** [manyeyes/AliParaformerAsr#12]
识别错误，python版能识别正确，python版的模型导出为onnx也不行

**Comment by manyeyes** [comment]
请提供测试音频和报错信息，以及你导出的模型版本或者链接

**Comment by iebcn309** [comment]
[1.zip](https://github.com/user-attachments/files/15942562/1.zip)
调用方式就是默认的

**Comment by manyeyes** [comment]
你提供的音频，听起来，难以确定说话内容，请给出参照文本

**Comment by iebcn309** [comment]
这是python版的识别结果：[{'key': '1', 'text': '看到没有？来这是谁，那这谁这个你不认识。', 'timestamp': [[620, 740], [740, 860], [860, 960], [960, 1200], [1300, 1540], [1560, 1640], [1640, 1800], [1800, 2040], [2680, 2920], [2940, 3060], [3060, 3300], [3820, 4000], [4000, 4080], [4080, 4160], [4160, 4240], [4240, 4400], [4400, 4725]]}]

**Comment by iebcn309** [comment]
用的这个demo:model = AutoModel(
    model="iic/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch",
    vad_model="iic/speech_fsmn_vad_zh-cn-16k-common-pytorch",
    vad_kwargs={"max_single_segment_time": 60000},
    punc_model="iic/punc_ct-transformer_zh-cn-common-vocab272727-pytorch",
    # spk_model="iic/speech_campplus_sv_zh-cn_16k-common",
)

**Comment by manyeyes** [comment]
采样率不对，需要转为16k。
转采样后识别结果如下：
`
loading_the_model_elapsed_milliseconds:2951.859375
看到没有来这是谁那这谁这个你不认识
看:[0,610]
到:[610,750]
没:[750,870]
有:[870,989]
来:[989,1329]
这:[1329,1530]
是:[1530,1630]
谁:[1630,1730]
那:[2669,2929]
这:[2929,3050]
谁:[3830,4009]
这:[4009,4089]
个:[4089,4170]
你:[4170,4250]
不:[4250,4410]
认:[4410,5634]
识:[5634,6779]
elapsed_milliseconds:302.8359375
total_duration:5688.875
rtf:0.05323300960207422
Hello, World!
`

**Comment by manyeyes** [comment]
Resampling, supports Windows platform
https://github.com/manyeyes/AliParaformerAsr/pull/13
