### ISSUE TITLE
请问这个能添加热词吗？

### ISSUE THREAD

**Issue by Cloud66666666** [manyeyes/AliParaformerAsr#16]
请问这个能添加热词吗？

**Comment by Xinayin** [comment]
同问

**Comment by manyeyes** [comment]
可以加

**Comment by manyeyes** [comment]
Supported SeACo-Paraformer (hotword) model：
https://github.com/manyeyes/AliParaformerAsr/pull/33
The code has been merged.
@Cloud66666666  @Xinayin

**Comment by zhilangtaosha** [comment]
怎么用python调取这些模型

**Comment by manyeyes** [comment]
> 怎么用python调取这些模型

[Use Funasr](https://github.com/modelscope/FunASR)
