### ISSUE TITLE
请问识别结果可以带上时间戳吗

### ISSUE THREAD

**Issue by dfengpo** [manyeyes/AliParaformerAsr#2]
请问识别结果可以带上时间戳吗，这个要怎么实现，是否可以提供一下思路，另外说话人识别是否可以提供一个示例？
万分感谢。
比如使用这个[https://www.modelscope.cn/models/iic/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-onnx/summary](url)

模型是支持时间戳的，但是C#调用中，怎么能获取到时间戳信息。

**Comment by manyeyes** [comment]
时间戳的实现有两个方法：
1.使用带时间戳的paraformer模型，解码后将输出token级别的时间戳，而英文的输出已将token合并为word.
2.使用vad，解码后输出音频分段segment samples，以及分段对应的时间戳。
   然后将segment 作为参数，调用AliParaformerAsr进行识别。
