### ISSUE TITLE
testing examples , error ErrorCode:InvalidProtobuf

### ISSUE THREAD

**Issue by kenchan97** [manyeyes/AliParaformerAsr#25]
model from "git clone https://www.modelscope.cn/manyeyes/sensevoice-small-onnx.git"

dotnet /tmp/test/AliParaformerAsr.Examples.dll
Unhandled exception. Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:InvalidProtobuf] Load model from /tmp/test/./sensevoice-small-onnx/model.int8.onnx failed:Protobuf parsing failed.
   at Microsoft.ML.OnnxRuntime.InferenceSession.Init(String modelPath, SessionOptions options, PrePackedWeightsContainer prepackedWeightsContainer)
   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath, SessionOptions options)

**Comment by manyeyes** [comment]
1.Whether to install and enable git lfs.
2.Check if the model exists or if its size is normal in the local path.

**Comment by manyeyes** [comment]
This issue has been pending for too long and will be closed. If the problem is still unresolved, please raise the issue again
