### ISSUE TITLE
大佬，没做资源释放吗

### ISSUE THREAD

**Issue by a869072989** [manyeyes/AliParaformerAsr#28]
我看有些地方没有Dispose,运行次数多了 就挂了。。。

**Comment by a869072989** [comment]
nothing

**Comment by manyeyes** [comment]
每处资源都有释放的。建议贴出你的调用方式，或者指明没释放的地方

**Comment by manyeyes** [comment]
你好，issue打开的时间太短，以至未留意。
离线识别的资源释放方式，在任务结束时，调用：offlineRecognizer.Dispose();
流式识别的资源释放方式，在任务结束时，调用：onlineRecognizer.Dispose();

**Comment by manyeyes** [comment]
资源释放的方式非常简单。
识别多个文件，不需要多次加载模型，具体请参照示例。
正确调用的情况，资源消耗稳定，内存占用与模型大小相当。
