### ISSUE TITLE
有流式模型调用的案例吗？

### ISSUE THREAD

**Issue by EitanWong** [manyeyes/AliParaformerAsr#3]

**Comment by manyeyes** [comment]
@EitanWong  流式调用示例：https://github.com/manyeyes/AliParaformerAsr/blob/master/AliParaformerAsr.Examples/OnlineRecognizer.cs

**Comment by toolgood** [comment]
实时（流式）模型 哪里下载

**Comment by manyeyes** [comment]
> 实时（流式）模型 哪里下载

https://modelscope.cn/models/manyeyes/aliparaformerasr-large-model-online/files
